application: flappy-bird-web
version: 2
runtime: python27
api_version: 1
threadsafe: true

default_expiration: 1d

handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico
- url: /static
  static_dir: static
- url: /.*
  script: app.app

inbound_services:
- warmup
